plugins:
  - jsdoc

extends:
  - raven
  - plugin:jsdoc/recommended

ignorePatterns:
  - node_modules/

rules:
  jsdoc/require-jsdoc:
  - error
  - require:
      ArrowFunctionExpression: true
      ClassExpression: true
      FunctionDeclaration: true
      MethodDefinition: true
  jsdoc/require-param-type: 0
  jsdoc/require-returns-type: 0

  no-trailing-spaces: [error, { ignoreComments: true }]
  multiline-comment-style: [error, separate-lines]
  id-length: [warn, { exceptions: [i, j, k, $] }]
  new-cap: ["error", { "capIsNewExceptionPattern": "^GM_" }]
  linebreak-style: 0
  sort-keys: 0
  no-labels: 0
  no-undef: 0
  no-magic-numbers: 0

env:
  browser: true
  node: false
